/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/warehousecompres.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFNode = THREE.Object3D & {
  geometry: THREE.BufferGeometry
}

type GLTFResult = GLTF & {
  nodes: Record<string, GLTFNode>
  materials: Record<string, THREE.Material>
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/warehousecompres.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Material2.geometry} material={materials['Metal21-basecolor']} position={[28.304, -1.128, 87.549]} scale={239.835} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.material} position={[25.936, 75.201, 73.906]} scale={236.842} />
        <mesh geometry={nodes.Material3.geometry} material={materials.material_0} position={[25.936, 8.606, 90.483]} scale={236.842} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials['Wood05-basecolor']} position={[25.936, 76.306, 74.031]} scale={236.592} />
        <lineSegments geometry={nodes.Material2_3.geometry} material={materials.edge_color000255} position={[25.936, 75.201, 74.344]} scale={236.842} />
        <mesh geometry={nodes.Material2_4.geometry} material={materials.Metal} position={[118.709, 35.998, 61.197]} scale={156.181} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials.Blackout} position={[-5.298, -17.936, 96.344]} scale={279} />
        <mesh geometry={nodes.Material2_6.geometry} material={materials.Wall} position={[-5.298, -20.436, 96.344]} scale={274} />
        <mesh geometry={nodes.Material2_7.geometry} material={materials.Floor} position={[-5.298, -19.998, 0]} scale={274} />
        <mesh geometry={nodes.Material2_8.geometry} material={materials.Ceiling} position={[-5.298, -20.436, 184.142]} scale={274} />
        <mesh geometry={nodes.Material2_9.geometry} material={materials.window} position={[66.741, 12.773, 96.688]} scale={208.148} />
        <mesh geometry={nodes.Material3_1.geometry} material={materials.Light} position={[-5.298, -41.456, 174.388]} scale={48} />
        <mesh geometry={nodes.Material2_10.geometry} material={materials.material_12} position={[20.604, 74.165, 47.755]} scale={181.406} />
        <mesh geometry={nodes.Material2_11.geometry} material={materials.material_12} position={[40.862, 68.188, 52.675]} scale={200.803} />
        <mesh geometry={nodes.Material2_12.geometry} material={materials.material_12} position={[137.753, 75.054, 28.996]} scale={103.944} />
        <mesh geometry={nodes.Material2_13.geometry} material={materials.material_12} position={[33.55, 94.015, 23.288]} scale={19.33} />
      </group>
    </group>
  )
}

useGLTF.preload('/warehousecompres.glb')
