import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Pharmasync",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased h-full`}>
			<body className="font-[family-name:var(--font-geist-sans)]">
				<SidebarProvider>
					<AppSidebar />
					<main className="flex flex-col flex-1 w-full overflow-x-hidden">
						<div className="p-4 border-b bg-white flex items-center gap-2">
							<SidebarTrigger />
						</div>
						<div className="flex-1 overflow-y-auto">
							{children}
						</div>
					</main>
				</SidebarProvider>
			</body>
		</html>
	);
}
